version: 2
jobs:
  build:
    environment: 
      - PACKAGE_PATH: "github.com/inloco/4apps"
      - GO111MODULE: "on"
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/inloco/go-wasabi

    steps:
      - checkout
      - run:
          name: Run tests
          environment:
          command: make test
